### ISSUE TITLE
Problem running demo_inference.py

### ISSUE THREAD

**Issue by parthplc** [codeaway23/number-plate-detection#4]
Use tf.where in 2.0, which has the same broadcast rule as np.where
Traceback (most recent call last):
  File "demo_inference.py", line 97, in <module>
    tf.app.run()
  File "/home/parth/anaconda3/envs/ocr/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/parth/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/parth/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "demo_inference.py", line 91, in main
    FLAGS.image_path_pattern)
  File "demo_inference.py", line 78, in run
    dataset_name)
  File "demo_inference.py", line 53, in load_images
    pil_image = PIL.Image.open(tf.gfile.GFile(file_pattern))
  File "/home/parth/.local/lib/python3.6/site-packages/PIL/Image.py", line 2775, in open
    prefix = fp.read(16)
  File "/home/parth/anaconda3/envs/ocr/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 128, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length))
  File "/home/parth/anaconda3/envs/ocr/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 98, in _prepare_value
    return compat.as_str_any(val)
  File "/home/parth/anaconda3/envs/ocr/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 117, in as_str_any
    return as_str(value)
  File "/home/parth/anaconda3/envs/ocr/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 87, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
I have succesfully trained the model using train.py and now using the saved model to use demo_inference.py but its throwing this error again and again.

**Comment by parthplc** [comment]
Hey @codeaway23 I think there might be an issue with demo_inference.py that you have created.

def load_images(file_pattern, batch_size, dataset_name):
  width, height = get_dataset_image_size(dataset_name)
  images_actual_data = np.ndarray(shape=(batch_size, height, width, 3),
                                  dtype='uint8')
  for i in range(batch_size):
    path = file_pattern % i
    print("Reading %s" % path)
    pil_image = PIL.Image.open(tf.gfile.GFile(file_pattern))
    images_actual_data[i, ...] = np.asarray(pil_image)
  return images_actual_data

In pil_image you must pass the path and not the file_pattern to otherwise that will create the above error.This was true in my case!!

**Comment by Ram-Godavarthi** [comment]
Traceback (most recent call last):
  File "demo_inference.py", line 96, in <module>
    tf.app.run()
  File "/home/ram/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "demo_inference.py", line 90, in main
    FLAGS.image_path_pattern)
  File "demo_inference.py", line 77, in run
    dataset_name)
  File "demo_inference.py", line 49, in load_images
    path = file_pattern %i
TypeError: not all arguments converted during string formatting

getting this error if i run the demo_inference as you mentioned.

@vapyc What is the solution?
